// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * TrayService manages the system tray icon, labels, window visibility, and desktop notifications.
 */
export class TrayService {

    /** Creates a new TrayService instance. */
    constructor($$source: Partial<TrayService> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrayService instance from a string or object.
     */
    static createFrom($$source: any = {}): TrayService {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrayService($$parsedSource as Partial<TrayService>);
    }
}
