// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config holds the user settings for Gittar.
 */
export class Config {
    "gitlabUrl": string;
    "token": string;
    "monitoredGroups": string[];
    "monitoredProjects": string[];
    "pollIntervalSec": number;
    "notifications": NotificationSettings;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("gitlabUrl" in $$source)) {
            this["gitlabUrl"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("monitoredGroups" in $$source)) {
            this["monitoredGroups"] = [];
        }
        if (!("monitoredProjects" in $$source)) {
            this["monitoredProjects"] = [];
        }
        if (!("pollIntervalSec" in $$source)) {
            this["pollIntervalSec"] = 0;
        }
        if (!("notifications" in $$source)) {
            this["notifications"] = (new NotificationSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("monitoredGroups" in $$parsedSource) {
            $$parsedSource["monitoredGroups"] = $$createField2_0($$parsedSource["monitoredGroups"]);
        }
        if ("monitoredProjects" in $$parsedSource) {
            $$parsedSource["monitoredProjects"] = $$createField3_0($$parsedSource["monitoredProjects"]);
        }
        if ("notifications" in $$parsedSource) {
            $$parsedSource["notifications"] = $$createField5_0($$parsedSource["notifications"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

/**
 * NotificationSettings contains fine-tuned preferences for desktop alerts.
 */
export class NotificationSettings {
    "enabled": boolean;
    "pipelineSuccess": boolean;
    "pipelineFailed": boolean;
    "mrAssigned": boolean;
    "mrReviewRequest": boolean;
    "todoMention": boolean;
    "todoAssignment": boolean;
    "todoIssue": boolean;
    "todoGeneric": boolean;

    /** Creates a new NotificationSettings instance. */
    constructor($$source: Partial<NotificationSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("pipelineSuccess" in $$source)) {
            this["pipelineSuccess"] = false;
        }
        if (!("pipelineFailed" in $$source)) {
            this["pipelineFailed"] = false;
        }
        if (!("mrAssigned" in $$source)) {
            this["mrAssigned"] = false;
        }
        if (!("mrReviewRequest" in $$source)) {
            this["mrReviewRequest"] = false;
        }
        if (!("todoMention" in $$source)) {
            this["todoMention"] = false;
        }
        if (!("todoAssignment" in $$source)) {
            this["todoAssignment"] = false;
        }
        if (!("todoIssue" in $$source)) {
            this["todoIssue"] = false;
        }
        if (!("todoGeneric" in $$source)) {
            this["todoGeneric"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationSettings($$parsedSource as Partial<NotificationSettings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = NotificationSettings.createFrom;
