// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config holds the user settings for Gittar.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("gitlabUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gitlabUrl"] = "";
        }
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }
        if (!("monitoredGroups" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["monitoredGroups"] = [];
        }
        if (!("monitoredProjects" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["monitoredProjects"] = [];
        }
        if (!("pollIntervalSec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pollIntervalSec"] = 0;
        }
        if (!("notifications" in $$source)) {
            /**
             * @member
             * @type {NotificationSettings}
             */
            this["notifications"] = (new NotificationSettings());
        }
        if (!("ignoreFailedPipelines" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ignoreFailedPipelines"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("monitoredGroups" in $$parsedSource) {
            $$parsedSource["monitoredGroups"] = $$createField2_0($$parsedSource["monitoredGroups"]);
        }
        if ("monitoredProjects" in $$parsedSource) {
            $$parsedSource["monitoredProjects"] = $$createField3_0($$parsedSource["monitoredProjects"]);
        }
        if ("notifications" in $$parsedSource) {
            $$parsedSource["notifications"] = $$createField5_0($$parsedSource["notifications"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * NotificationSettings contains fine-tuned preferences for desktop alerts.
 */
export class NotificationSettings {
    /**
     * Creates a new NotificationSettings instance.
     * @param {Partial<NotificationSettings>} [$$source = {}] - The source object to create the NotificationSettings.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("pipelineSuccess" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pipelineSuccess"] = false;
        }
        if (!("pipelineFailed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pipelineFailed"] = false;
        }
        if (!("mrAssigned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mrAssigned"] = false;
        }
        if (!("mrReviewRequest" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mrReviewRequest"] = false;
        }
        if (!("todoMention" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["todoMention"] = false;
        }
        if (!("todoAssignment" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["todoAssignment"] = false;
        }
        if (!("todoIssue" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["todoIssue"] = false;
        }
        if (!("todoGeneric" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["todoGeneric"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NotificationSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationSettings(/** @type {Partial<NotificationSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = NotificationSettings.createFrom;
