// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * HeadPipeline represents the pipeline for the head commit of a Merge Request.
 */
export class HeadPipeline {
    /**
     * Creates a new HeadPipeline instance.
     * @param {Partial<HeadPipeline>} [$$source = {}] - The source object to create the HeadPipeline.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("web_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["web_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeadPipeline instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HeadPipeline}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeadPipeline(/** @type {Partial<HeadPipeline>} */($$parsedSource));
    }
}

/**
 * Job represents a GitLab Job.
 */
export class Job {
    /**
     * Creates a new Job instance.
     * @param {Partial<Job>} [$$source = {}] - The source object to create the Job.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ref" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ref"] = "";
        }
        if (!("web_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["web_url"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * in seconds
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["finished_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Job}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Job(/** @type {Partial<Job>} */($$parsedSource));
    }
}

/**
 * MergeRequest represents a GitLab Merge Request.
 */
export class MergeRequest {
    /**
     * Creates a new MergeRequest instance.
     * @param {Partial<MergeRequest>} [$$source = {}] - The source object to create the MergeRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("iid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iid"] = 0;
        }
        if (!("project_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["project_id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("target_branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_branch"] = "";
        }
        if (!("source_branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_branch"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {User}
             */
            this["author"] = (new User());
        }
        if (!("assignees" in $$source)) {
            /**
             * @member
             * @type {User[]}
             */
            this["assignees"] = [];
        }
        if (!("reviewers" in $$source)) {
            /**
             * @member
             * @type {User[]}
             */
            this["reviewers"] = [];
        }
        if (!("web_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["web_url"] = "";
        }
        if (!("user_notes_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["user_notes_count"] = 0;
        }
        if (!("upvotes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["upvotes"] = 0;
        }
        if (!("downvotes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downvotes"] = 0;
        }
        if (!("work_in_progress" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["work_in_progress"] = false;
        }
        if (!("draft" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["draft"] = false;
        }
        if (!("labels" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["labels"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {HeadPipeline | null | undefined}
             */
            this["head_pipeline"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated_at"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["merged_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["closed_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeRequest}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType1;
        const $$createField17_0 = $$createType2;
        const $$createField18_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField8_0($$parsedSource["author"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField9_0($$parsedSource["assignees"]);
        }
        if ("reviewers" in $$parsedSource) {
            $$parsedSource["reviewers"] = $$createField10_0($$parsedSource["reviewers"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField17_0($$parsedSource["labels"]);
        }
        if ("head_pipeline" in $$parsedSource) {
            $$parsedSource["head_pipeline"] = $$createField18_0($$parsedSource["head_pipeline"]);
        }
        return new MergeRequest(/** @type {Partial<MergeRequest>} */($$parsedSource));
    }
}

/**
 * Pipeline represents a GitLab Pipeline.
 */
export class Pipeline {
    /**
     * Creates a new Pipeline instance.
     * @param {Partial<Pipeline>} [$$source = {}] - The source object to create the Pipeline.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("iid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iid"] = 0;
        }
        if (!("project_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["project_id"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * running, pending, success, failed, canceled, skipped, manual
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("ref" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ref"] = "";
        }
        if (!("sha" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha"] = "";
        }
        if (!("web_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["web_url"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated_at"] = null;
        }
        if (!("duration" in $$source)) {
            /**
             * in seconds
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {User}
             */
            this["user"] = (new User());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pipeline instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Pipeline}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField10_0($$parsedSource["user"]);
        }
        return new Pipeline(/** @type {Partial<Pipeline>} */($$parsedSource));
    }
}

/**
 * PipelineWithJobs bundles a pipeline with its current jobs and project context.
 */
export class PipelineWithJobs {
    /**
     * Creates a new PipelineWithJobs instance.
     * @param {Partial<PipelineWithJobs>} [$$source = {}] - The source object to create the PipelineWithJobs.
     */
    constructor($$source = {}) {
        if (!("pipeline" in $$source)) {
            /**
             * @member
             * @type {Pipeline}
             */
            this["pipeline"] = (new Pipeline());
        }
        if (!("jobs" in $$source)) {
            /**
             * @member
             * @type {Job[]}
             */
            this["jobs"] = [];
        }
        if (!("projectName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectName"] = "";
        }
        if (!("projectPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PipelineWithJobs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PipelineWithJobs}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pipeline" in $$parsedSource) {
            $$parsedSource["pipeline"] = $$createField0_0($$parsedSource["pipeline"]);
        }
        if ("jobs" in $$parsedSource) {
            $$parsedSource["jobs"] = $$createField1_0($$parsedSource["jobs"]);
        }
        return new PipelineWithJobs(/** @type {Partial<PipelineWithJobs>} */($$parsedSource));
    }
}

/**
 * ProjectRef represents a simplified project reference.
 */
export class ProjectRef {
    /**
     * Creates a new ProjectRef instance.
     * @param {Partial<ProjectRef>} [$$source = {}] - The source object to create the ProjectRef.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path_with_namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path_with_namespace"] = "";
        }
        if (!("web_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["web_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectRef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectRef(/** @type {Partial<ProjectRef>} */($$parsedSource));
    }
}

/**
 * TelemetryPayload is the unified status update pushed to the frontend.
 */
export class TelemetryPayload {
    /**
     * Creates a new TelemetryPayload instance.
     * @param {Partial<TelemetryPayload>} [$$source = {}] - The source object to create the TelemetryPayload.
     */
    constructor($$source = {}) {
        if (!("todos" in $$source)) {
            /**
             * @member
             * @type {Todo[]}
             */
            this["todos"] = [];
        }
        if (!("pipelines" in $$source)) {
            /**
             * @member
             * @type {PipelineWithJobs[]}
             */
            this["pipelines"] = [];
        }
        if (!("mergeRequests" in $$source)) {
            /**
             * @member
             * @type {MergeRequest[]}
             */
            this["mergeRequests"] = [];
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("avatarUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatarUrl"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TelemetryPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TelemetryPayload}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType11;
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("todos" in $$parsedSource) {
            $$parsedSource["todos"] = $$createField0_0($$parsedSource["todos"]);
        }
        if ("pipelines" in $$parsedSource) {
            $$parsedSource["pipelines"] = $$createField1_0($$parsedSource["pipelines"]);
        }
        if ("mergeRequests" in $$parsedSource) {
            $$parsedSource["mergeRequests"] = $$createField2_0($$parsedSource["mergeRequests"]);
        }
        return new TelemetryPayload(/** @type {Partial<TelemetryPayload>} */($$parsedSource));
    }
}

/**
 * Todo represents a GitLab Todo item.
 */
export class Todo {
    /**
     * Creates a new Todo instance.
     * @param {Partial<Todo>} [$$source = {}] - The source object to create the Todo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("project" in $$source)) {
            /**
             * @member
             * @type {ProjectRef}
             */
            this["project"] = (new ProjectRef());
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {User}
             */
            this["author"] = (new User());
        }
        if (!("action_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["action_name"] = "";
        }
        if (!("target_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_type"] = "";
        }
        if (!("target_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_url"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Todo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Todo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType14;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField1_0($$parsedSource["project"]);
        }
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField2_0($$parsedSource["author"]);
        }
        return new Todo(/** @type {Partial<Todo>} */($$parsedSource));
    }
}

/**
 * User represents a GitLab user.
 */
export class User {
    /**
     * Creates a new User instance.
     * @param {Partial<User>} [$$source = {}] - The source object to create the User.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("avatar_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatar_url"] = "";
        }
        if (!("web_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["web_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {User}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User(/** @type {Partial<User>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = User.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = HeadPipeline.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = Pipeline.createFrom;
const $$createType6 = Job.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Todo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = PipelineWithJobs.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = MergeRequest.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = ProjectRef.createFrom;
