// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * HeadPipeline represents the pipeline for the head commit of a Merge Request.
 */
export class HeadPipeline {
    "id": number;
    "status": string;
    "web_url": string;

    /** Creates a new HeadPipeline instance. */
    constructor($$source: Partial<HeadPipeline> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("web_url" in $$source)) {
            this["web_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HeadPipeline instance from a string or object.
     */
    static createFrom($$source: any = {}): HeadPipeline {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HeadPipeline($$parsedSource as Partial<HeadPipeline>);
    }
}

/**
 * Issue represents a GitLab Issue.
 */
export class Issue {
    "id": number;
    "iid": number;
    "project_id": number;
    "title": string;
    "description": string;
    "state": string;
    "author": User;
    "assignees": User[];
    "labels": string[];
    "web_url": string;
    "user_notes_count": number;
    "upvotes": number;
    "downvotes": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "closed_at"?: time$0.Time | null;

    /** Creates a new Issue instance. */
    constructor($$source: Partial<Issue> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("iid" in $$source)) {
            this["iid"] = 0;
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = (new User());
        }
        if (!("assignees" in $$source)) {
            this["assignees"] = [];
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }
        if (!("web_url" in $$source)) {
            this["web_url"] = "";
        }
        if (!("user_notes_count" in $$source)) {
            this["user_notes_count"] = 0;
        }
        if (!("upvotes" in $$source)) {
            this["upvotes"] = 0;
        }
        if (!("downvotes" in $$source)) {
            this["downvotes"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Issue instance from a string or object.
     */
    static createFrom($$source: any = {}): Issue {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField6_0($$parsedSource["author"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField7_0($$parsedSource["assignees"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField8_0($$parsedSource["labels"]);
        }
        return new Issue($$parsedSource as Partial<Issue>);
    }
}

/**
 * Job represents a GitLab Job.
 */
export class Job {
    "id": number;
    "status": string;
    "stage": string;
    "name": string;
    "ref": string;
    "web_url": string;

    /**
     * in seconds
     */
    "duration": number;
    "finished_at"?: time$0.Time | null;

    /** Creates a new Job instance. */
    constructor($$source: Partial<Job> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("stage" in $$source)) {
            this["stage"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("ref" in $$source)) {
            this["ref"] = "";
        }
        if (!("web_url" in $$source)) {
            this["web_url"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     */
    static createFrom($$source: any = {}): Job {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Job($$parsedSource as Partial<Job>);
    }
}

/**
 * MergeRequest represents a GitLab Merge Request.
 */
export class MergeRequest {
    "id": number;
    "iid": number;
    "project_id": number;
    "title": string;
    "description": string;
    "state": string;
    "target_branch": string;
    "source_branch": string;
    "author": User;
    "assignees": User[];
    "reviewers": User[];
    "web_url": string;
    "user_notes_count": number;
    "upvotes": number;
    "downvotes": number;
    "work_in_progress": boolean;
    "draft": boolean;
    "labels": string[];
    "head_pipeline"?: HeadPipeline | null;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "merged_at"?: time$0.Time | null;
    "closed_at"?: time$0.Time | null;

    /** Creates a new MergeRequest instance. */
    constructor($$source: Partial<MergeRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("iid" in $$source)) {
            this["iid"] = 0;
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("target_branch" in $$source)) {
            this["target_branch"] = "";
        }
        if (!("source_branch" in $$source)) {
            this["source_branch"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = (new User());
        }
        if (!("assignees" in $$source)) {
            this["assignees"] = [];
        }
        if (!("reviewers" in $$source)) {
            this["reviewers"] = [];
        }
        if (!("web_url" in $$source)) {
            this["web_url"] = "";
        }
        if (!("user_notes_count" in $$source)) {
            this["user_notes_count"] = 0;
        }
        if (!("upvotes" in $$source)) {
            this["upvotes"] = 0;
        }
        if (!("downvotes" in $$source)) {
            this["downvotes"] = 0;
        }
        if (!("work_in_progress" in $$source)) {
            this["work_in_progress"] = false;
        }
        if (!("draft" in $$source)) {
            this["draft"] = false;
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MergeRequest {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType1;
        const $$createField17_0 = $$createType2;
        const $$createField18_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField8_0($$parsedSource["author"]);
        }
        if ("assignees" in $$parsedSource) {
            $$parsedSource["assignees"] = $$createField9_0($$parsedSource["assignees"]);
        }
        if ("reviewers" in $$parsedSource) {
            $$parsedSource["reviewers"] = $$createField10_0($$parsedSource["reviewers"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField17_0($$parsedSource["labels"]);
        }
        if ("head_pipeline" in $$parsedSource) {
            $$parsedSource["head_pipeline"] = $$createField18_0($$parsedSource["head_pipeline"]);
        }
        return new MergeRequest($$parsedSource as Partial<MergeRequest>);
    }
}

/**
 * Pipeline represents a GitLab Pipeline.
 */
export class Pipeline {
    "id": number;
    "iid": number;
    "project_id": number;

    /**
     * running, pending, success, failed, canceled, skipped, manual
     */
    "status": string;
    "ref": string;
    "sha": string;
    "web_url": string;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /**
     * in seconds
     */
    "duration": number;
    "user": User;

    /** Creates a new Pipeline instance. */
    constructor($$source: Partial<Pipeline> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("iid" in $$source)) {
            this["iid"] = 0;
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("ref" in $$source)) {
            this["ref"] = "";
        }
        if (!("sha" in $$source)) {
            this["sha"] = "";
        }
        if (!("web_url" in $$source)) {
            this["web_url"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = (new User());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pipeline instance from a string or object.
     */
    static createFrom($$source: any = {}): Pipeline {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField10_0($$parsedSource["user"]);
        }
        return new Pipeline($$parsedSource as Partial<Pipeline>);
    }
}

/**
 * PipelineWithJobs bundles a pipeline with its current jobs and project context.
 */
export class PipelineWithJobs {
    "pipeline": Pipeline;
    "jobs": Job[];
    "projectName": string;
    "projectPath": string;

    /** Creates a new PipelineWithJobs instance. */
    constructor($$source: Partial<PipelineWithJobs> = {}) {
        if (!("pipeline" in $$source)) {
            this["pipeline"] = (new Pipeline());
        }
        if (!("jobs" in $$source)) {
            this["jobs"] = [];
        }
        if (!("projectName" in $$source)) {
            this["projectName"] = "";
        }
        if (!("projectPath" in $$source)) {
            this["projectPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PipelineWithJobs instance from a string or object.
     */
    static createFrom($$source: any = {}): PipelineWithJobs {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pipeline" in $$parsedSource) {
            $$parsedSource["pipeline"] = $$createField0_0($$parsedSource["pipeline"]);
        }
        if ("jobs" in $$parsedSource) {
            $$parsedSource["jobs"] = $$createField1_0($$parsedSource["jobs"]);
        }
        return new PipelineWithJobs($$parsedSource as Partial<PipelineWithJobs>);
    }
}

/**
 * ProjectRef represents a simplified project reference.
 */
export class ProjectRef {
    "id": number;
    "name": string;
    "path_with_namespace": string;
    "web_url": string;

    /** Creates a new ProjectRef instance. */
    constructor($$source: Partial<ProjectRef> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path_with_namespace" in $$source)) {
            this["path_with_namespace"] = "";
        }
        if (!("web_url" in $$source)) {
            this["web_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectRef instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectRef($$parsedSource as Partial<ProjectRef>);
    }
}

/**
 * TelemetryPayload is the unified status update pushed to the frontend.
 */
export class TelemetryPayload {
    "todos": Todo[];
    "pipelines": PipelineWithJobs[];
    "mergeRequests": MergeRequest[];
    "issues": Issue[];
    "username": string;
    "avatarUrl": string;
    "error"?: string;

    /** Creates a new TelemetryPayload instance. */
    constructor($$source: Partial<TelemetryPayload> = {}) {
        if (!("todos" in $$source)) {
            this["todos"] = [];
        }
        if (!("pipelines" in $$source)) {
            this["pipelines"] = [];
        }
        if (!("mergeRequests" in $$source)) {
            this["mergeRequests"] = [];
        }
        if (!("issues" in $$source)) {
            this["issues"] = [];
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("avatarUrl" in $$source)) {
            this["avatarUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TelemetryPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): TelemetryPayload {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType11;
        const $$createField2_0 = $$createType13;
        const $$createField3_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("todos" in $$parsedSource) {
            $$parsedSource["todos"] = $$createField0_0($$parsedSource["todos"]);
        }
        if ("pipelines" in $$parsedSource) {
            $$parsedSource["pipelines"] = $$createField1_0($$parsedSource["pipelines"]);
        }
        if ("mergeRequests" in $$parsedSource) {
            $$parsedSource["mergeRequests"] = $$createField2_0($$parsedSource["mergeRequests"]);
        }
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField3_0($$parsedSource["issues"]);
        }
        return new TelemetryPayload($$parsedSource as Partial<TelemetryPayload>);
    }
}

/**
 * Todo represents a GitLab Todo item.
 */
export class Todo {
    "id": number;
    "project": ProjectRef;
    "author": User;
    "action_name": string;
    "target_type": string;
    "target_url": string;
    "body": string;
    "state": string;
    "created_at": time$0.Time;

    /** Creates a new Todo instance. */
    constructor($$source: Partial<Todo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("project" in $$source)) {
            this["project"] = (new ProjectRef());
        }
        if (!("author" in $$source)) {
            this["author"] = (new User());
        }
        if (!("action_name" in $$source)) {
            this["action_name"] = "";
        }
        if (!("target_type" in $$source)) {
            this["target_type"] = "";
        }
        if (!("target_url" in $$source)) {
            this["target_url"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Todo instance from a string or object.
     */
    static createFrom($$source: any = {}): Todo {
        const $$createField1_0 = $$createType16;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField1_0($$parsedSource["project"]);
        }
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField2_0($$parsedSource["author"]);
        }
        return new Todo($$parsedSource as Partial<Todo>);
    }
}

/**
 * User represents a GitLab user.
 */
export class User {
    "id": number;
    "name": string;
    "username": string;
    "state": string;
    "avatar_url": string;
    "web_url": string;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("avatar_url" in $$source)) {
            this["avatar_url"] = "";
        }
        if (!("web_url" in $$source)) {
            this["web_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}

// Private type creation functions
const $$createType0 = User.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = HeadPipeline.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = Pipeline.createFrom;
const $$createType6 = Job.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Todo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = PipelineWithJobs.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = MergeRequest.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = Issue.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ProjectRef.createFrom;
