// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService handles bindings and telemetry orchestration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gitlab$0 from "../gitlab/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tray$0 from "../tray/models.js";

/**
 * FetchTelemetry fetches all telemetry data concurrently.
 */
export function FetchTelemetry(): $CancellablePromise<gitlab$0.TelemetryPayload | null> {
    return $Call.ByID(843013167).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetConfig reads the user config.
 */
export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(3673826530).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetJobLogSnippet fetches log tail for a specific failed job.
 */
export function GetJobLogSnippet(projectIDOrPath: string, jobID: number): $CancellablePromise<string> {
    return $Call.ByID(3512261036, projectIDOrPath, jobID);
}

/**
 * SaveConfig saves the user config.
 */
export function SaveConfig(conf: config$0.Config | null): $CancellablePromise<void> {
    return $Call.ByID(927934359, conf);
}

/**
 * SetTray links the system tray manager to the application service.
 */
export function SetTray(t: tray$0.TrayService | null): $CancellablePromise<void> {
    return $Call.ByID(3964840448, t);
}

// Private type creation functions
const $$createType0 = gitlab$0.TelemetryPayload.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.Config.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
