// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService handles bindings and telemetry orchestration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gitlab$0 from "../gitlab/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelPipeline cancels a running pipeline.
 */
export function CancelPipeline(projectPath: string, pipelineID: number): $CancellablePromise<void> {
    return $Call.ByID(1579050620, projectPath, pipelineID);
}

/**
 * ClearTelemetryCache flushes the GitLab client cache.
 */
export function ClearTelemetryCache(): $CancellablePromise<void> {
    return $Call.ByID(1916818586);
}

/**
 * CloseMergeRequest updates the GitLab MR state to closed.
 */
export function CloseMergeRequest(projectID: number, mrIID: number): $CancellablePromise<void> {
    return $Call.ByID(3025380849, projectID, mrIID);
}

/**
 * FetchTelemetry fetches all telemetry data concurrently.
 */
export function FetchTelemetry(): $CancellablePromise<gitlab$0.TelemetryPayload | null> {
    return $Call.ByID(843013167).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetCachedTelemetry reads the cached GitLab telemetry payload from disk.
 */
export function GetCachedTelemetry(): $CancellablePromise<gitlab$0.TelemetryPayload | null> {
    return $Call.ByID(3892731397).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetConfig reads the user config.
 */
export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(3673826530).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetJobLogSnippet fetches log tail for a specific failed job.
 */
export function GetJobLogSnippet(projectIDOrPath: string, jobID: number): $CancellablePromise<string> {
    return $Call.ByID(3512261036, projectIDOrPath, jobID);
}

/**
 * MarkTodoAsDone marks the pending todo as done.
 */
export function MarkTodoAsDone(todoID: number): $CancellablePromise<void> {
    return $Call.ByID(1491430789, todoID);
}

/**
 * MergeMergeRequest accepts/merges the GitLab MR.
 */
export function MergeMergeRequest(projectID: number, mrIID: number): $CancellablePromise<void> {
    return $Call.ByID(4151525513, projectID, mrIID);
}

/**
 * RetryPipeline retries a failed pipeline.
 */
export function RetryPipeline(projectPath: string, pipelineID: number): $CancellablePromise<void> {
    return $Call.ByID(4021497124, projectPath, pipelineID);
}

/**
 * SaveConfig saves the user config.
 */
export function SaveConfig(conf: config$0.Config | null): $CancellablePromise<void> {
    return $Call.ByID(927934359, conf);
}

/**
 * SetTray links the system tray manager to the application service.
 */
export function SetTray(t: $models.Notifier): $CancellablePromise<void> {
    return $Call.ByID(3964840448, t);
}

/**
 * TriggerTestNotification sends a test native notification.
 */
export function TriggerTestNotification(): $CancellablePromise<void> {
    return $Call.ByID(2058535599);
}

// Private type creation functions
const $$createType0 = gitlab$0.TelemetryPayload.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.Config.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
