// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService handles bindings and telemetry orchestration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gitlab$0 from "../gitlab/models.js";

/**
 * CancelPipeline cancels a running pipeline.
 */
export function CancelPipeline(projectPath: string, pipelineID: number): $CancellablePromise<void> {
    return $Call.ByID(1579050620, projectPath, pipelineID);
}

/**
 * ClearTelemetryCache flushes the GitLab client cache.
 */
export function ClearTelemetryCache(): $CancellablePromise<void> {
    return $Call.ByID(1916818586);
}

/**
 * CloseIssue updates the GitLab Issue state to closed.
 */
export function CloseIssue(projectID: number, issueIID: number): $CancellablePromise<void> {
    return $Call.ByID(858566815, projectID, issueIID);
}

/**
 * CloseMergeRequest updates the GitLab MR state to closed.
 */
export function CloseMergeRequest(projectID: number, mrIID: number): $CancellablePromise<void> {
    return $Call.ByID(3025380849, projectID, mrIID);
}

/**
 * CreateMergeRequestNote adds a comment to a merge request and clears the client cache to force fresh fetching.
 */
export function CreateMergeRequestNote(projectID: number, mrIID: number, body: string): $CancellablePromise<gitlab$0.Note | null> {
    return $Call.ByID(3045205465, projectID, mrIID, body).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FetchTelemetry fetches all telemetry data concurrently.
 */
export function FetchTelemetry(): $CancellablePromise<gitlab$0.TelemetryPayload | null> {
    return $Call.ByID(843013167).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetCachedTelemetry reads the cached GitLab telemetry payload from disk.
 */
export function GetCachedTelemetry(): $CancellablePromise<gitlab$0.TelemetryPayload | null> {
    return $Call.ByID(3892731397).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetConfig reads the user config.
 */
export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(3673826530).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetJobLogSnippet fetches log tail for a specific failed job.
 */
export function GetJobLogSnippet(projectIDOrPath: string, jobID: number): $CancellablePromise<string> {
    return $Call.ByID(3512261036, projectIDOrPath, jobID);
}

/**
 * GetMergeRequestCommits fetches commits for a merge request.
 */
export function GetMergeRequestCommits(projectID: number, mrIID: number): $CancellablePromise<gitlab$0.Commit[]> {
    return $Call.ByID(3049906921, projectID, mrIID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetMergeRequestNotes fetches notes/comments for a merge request.
 */
export function GetMergeRequestNotes(projectID: number, mrIID: number): $CancellablePromise<gitlab$0.Note[]> {
    return $Call.ByID(1523195622, projectID, mrIID).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetSingleMergeRequest fetches detailed information for a single MR from GitLab.
 */
export function GetSingleMergeRequest(projectID: number, mrIID: number): $CancellablePromise<gitlab$0.MergeRequest | null> {
    return $Call.ByID(3571403013, projectID, mrIID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * MarkTodoAsDone marks the pending todo as done.
 */
export function MarkTodoAsDone(todoID: number): $CancellablePromise<void> {
    return $Call.ByID(1491430789, todoID);
}

/**
 * MergeMergeRequest accepts/merges the GitLab MR.
 */
export function MergeMergeRequest(projectID: number, mrIID: number): $CancellablePromise<void> {
    return $Call.ByID(4151525513, projectID, mrIID);
}

/**
 * RetryPipeline retries a failed pipeline.
 */
export function RetryPipeline(projectPath: string, pipelineID: number): $CancellablePromise<void> {
    return $Call.ByID(4021497124, projectPath, pipelineID);
}

/**
 * SaveConfig saves the user config.
 */
export function SaveConfig(conf: config$0.Config | null): $CancellablePromise<void> {
    return $Call.ByID(927934359, conf);
}

/**
 * TriggerTestNotification sends a test native notification.
 */
export function TriggerTestNotification(): $CancellablePromise<void> {
    return $Call.ByID(2058535599);
}

// Private type creation functions
const $$createType0 = gitlab$0.Note.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = gitlab$0.TelemetryPayload.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = config$0.Config.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = gitlab$0.Commit.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($$createType0);
const $$createType9 = gitlab$0.MergeRequest.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
