// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService handles bindings and telemetry orchestration.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gitlab$0 from "../gitlab/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tray$0 from "../tray/models.js";

/**
 * CancelPipeline cancels a running pipeline.
 * @param {string} projectPath
 * @param {number} pipelineID
 * @returns {$CancellablePromise<void>}
 */
export function CancelPipeline(projectPath, pipelineID) {
    return $Call.ByID(1579050620, projectPath, pipelineID);
}

/**
 * CloseMergeRequest updates the GitLab MR state to closed.
 * @param {number} projectID
 * @param {number} mrIID
 * @returns {$CancellablePromise<void>}
 */
export function CloseMergeRequest(projectID, mrIID) {
    return $Call.ByID(3025380849, projectID, mrIID);
}

/**
 * FetchTelemetry fetches all telemetry data concurrently.
 * @returns {$CancellablePromise<gitlab$0.TelemetryPayload | null>}
 */
export function FetchTelemetry() {
    return $Call.ByID(843013167).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetCachedTelemetry reads the cached GitLab telemetry payload from disk.
 * @returns {$CancellablePromise<gitlab$0.TelemetryPayload | null>}
 */
export function GetCachedTelemetry() {
    return $Call.ByID(3892731397).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetConfig reads the user config.
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(3673826530).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetJobLogSnippet fetches log tail for a specific failed job.
 * @param {string} projectIDOrPath
 * @param {number} jobID
 * @returns {$CancellablePromise<string>}
 */
export function GetJobLogSnippet(projectIDOrPath, jobID) {
    return $Call.ByID(3512261036, projectIDOrPath, jobID);
}

/**
 * MarkTodoAsDone marks the pending todo as done.
 * @param {number} todoID
 * @returns {$CancellablePromise<void>}
 */
export function MarkTodoAsDone(todoID) {
    return $Call.ByID(1491430789, todoID);
}

/**
 * MergeMergeRequest accepts/merges the GitLab MR.
 * @param {number} projectID
 * @param {number} mrIID
 * @returns {$CancellablePromise<void>}
 */
export function MergeMergeRequest(projectID, mrIID) {
    return $Call.ByID(4151525513, projectID, mrIID);
}

/**
 * RetryPipeline retries a failed pipeline.
 * @param {string} projectPath
 * @param {number} pipelineID
 * @returns {$CancellablePromise<void>}
 */
export function RetryPipeline(projectPath, pipelineID) {
    return $Call.ByID(4021497124, projectPath, pipelineID);
}

/**
 * SaveConfig saves the user config.
 * @param {config$0.Config | null} conf
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(conf) {
    return $Call.ByID(927934359, conf);
}

/**
 * SetTray links the system tray manager to the application service.
 * @param {tray$0.TrayService | null} t
 * @returns {$CancellablePromise<void>}
 */
export function SetTray(t) {
    return $Call.ByID(3964840448, t);
}

// Private type creation functions
const $$createType0 = gitlab$0.TelemetryPayload.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.Config.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
